name: penn_fudan_ped

mode: generate

data_dir: data
data_filter: "PNGImages/*6.png"
label_filter: "PedMasks/*6_mask.png"

process: code.data_slicer:PennFudanPedSlicer
pip_req: requirements.txt

desc: PennFudanPed data and label test dataset
tag:
 - bin

attr:
  batch_size: 1
  alignment_size: 4k
  volume_size: 2M
