client:
  - "**/*.py"
  - "client/**"

console:
  - "console/**"

docker:
  - "docker/**"

server:
  - "**/*.java"
  - "server/**"

server_api:
  - "server/controller/src/main/java/ai/starwhale/mlops/api/**"

docs:
  - "docs/**"

scripts:
  - "scripts/**"

js:
  - "**/*.js"
  - "**/*.jsx"
  - "**/*.ts"
  - "**/*.tsx"

scss:
  - "**/*.scss"

java:
  - "**/*.java"

charts:
  - "docker/charts/**"
