
{{ if .Values.controller.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: controller
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 30g

spec:
  ingressClassName: {{ .Values.controller.ingress.ingressClassName }}
  rules:
  {{- if .Values.minikube }}
    - host: controller.{{ .Release.Namespace }}.svc
  {{- else }}
    - host: {{ .Values.controller.ingress.host }}
  {{- end}}
      http:
        paths:
          - path: {{ .Values.controller.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: controller
                port:
                  number: {{ .Values.controller.containerPort }}
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "chart.controller.labels" . | nindent 4}}
spec:
  ports:
    - port: {{ .Values.controller.containerPort }}
      protocol: TCP
  selector:
    {{ include "chart.controller.labels" . | nindent 4}}