{{ if .Values.minikube.enabled}}

{{ if eq .Values.controller.storageType "fs"}}
{{ include "chart.minikubePV" (merge (dict "backend" "controller") . )}}
{{ else }}
{{ if .Values.minio.enabled }}
{{ include "chart.minikubePV" (merge (dict "backend" "minio") . )}}
{{ end }}
{{ end }}

{{ if .Values.mysql.enabled }}
{{ include "chart.minikubePV" (merge (dict "backend" "mysql") . )}}
{{ end }}

{{ end }}


{{ if .Values.devMode.createPV.enabled }}

{{ $params := (merge (dict "rootPath" .Values.devMode.createPV.rootPath) . ) }}

{{ if eq .Values.controller.storageType "fs"}}
{{ include "chart.createPV" (merge (dict "backend" "controller" "storage" .Values.controller.persistence.size) $params) }}
{{ else }}
{{ if .Values.minio.enabled }}
{{ include "chart.createPV" (merge (dict "backend" "minio" "storage" .Values.minio.persistence.size) $params) }}
{{ end }}
{{ end }}

{{ if .Values.mysql.enabled }}
{{ include "chart.createPV" (merge (dict "backend" "mysql" "storage" .Values.mysql.persistence.size) $params) }}
{{ end }}

{{ end }}
