{{- if .Values.rbac.create }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
{{- if .Values.rbac.clusterAdminRole }}
  name: cluster-admin
{{- else }}
  name: {{ .Values.rbac.customClusterRole }}
{{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.names.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
