apiVersion: batch/v1
kind: Job
metadata:
  name: 'build-job'
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: 'prepare-runtime'
          imagePullPolicy: IfNotPresent
          image: 'ghcr.io/star-whale/starwhale:latest'
          volumeMounts:
            - mountPath: /opt/starwhale.user/runtime
              name: data
          command:
            - sh
            - -c
            - >-
              set -x;
              swcli instance login --token="$SW_TOKEN" --alias server $SW_INSTANCE_URI;
              swcli runtime copy cloud://server/project/$SW_PROJECT/runtime/$SW_RUNTIME_VERSION .;
              swcli runtime extract  --target-dir /opt/starwhale.user/runtime $SW_RUNTIME_VERSION;
              swcli runtime dockerize -t gxx-test --push --dry-run --use-starwhale-builder --reset-qemu-static $SW_RUNTIME_VERSION;
              _SNAPSHOT_DIR=$(swcli -o json runtime info ${SW_RUNTIME_VERSION} | jq -r ".snapshot_workdir");
              cp $_SNAPSHOT_DIR/export/docker/Dockerfile /opt/starwhale.user/runtime || exit 1;
      containers:
        - name: 'image-builder'
          image: 'gcr.io/kaniko-project/executor:latest'
          args: [ "--dockerfile=Dockerfile",
                  "--context=dir:///workspace"] # --destination=10.131.0.1:8083/test/build:1.1.0 replace with your dockerhub account
          volumeMounts:
            - name: kaniko-secret
              mountPath: /kaniko/.docker
            - name: data
              mountPath: /workspace # should be workspace otherwise some layer would loos
      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: data
          emptyDir: { }
