apiVersion: batch/v1
kind: Job
metadata:
  name: 'indexed-job'
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: data-provider
          imagePullPolicy: IfNotPresent
          image: amazon/aws-cli:2.7.25
          volumeMounts:
            - mountPath: /opt/starwhale
              name: data
          command: ["/bin/sh"]
          args: ["-c", "for item in $DOWNLOADS; do SRC=$(echo $item|cut -d';' -f1) && DST=$(echo $item|cut -d';' -f2) && echo $SRC,$DST && mkdir -p $DST && aws --endpoint-url=$ENDPOINT_URL --region=$AWS_S3_REGION s3 cp --recursive $SRC $DST; done"]
        - name: untar
          imagePullPolicy: IfNotPresent
          image: ghcr.io/star-whale/starwhale:latest
          volumeMounts:
            - mountPath: /opt/starwhale
              name: data
          command:
            - sh
            - -c
            - >-
              cd /opt/starwhale && find ./ -type f \( -name \*.swmp -o -name \*.swrt \) -exec tar -C swmp/ -xf {} \;
        - name: 'worker'
          image: 'docker.io/library/busybox'
          imagePullPolicy: IfNotPresent
          args:
            - ppl
          volumeMounts:
            - mountPath: /root/.cache
              name: pip-cache
            - mountPath: /opt/starwhale
              name: data
          env:
            - name: SW_PYPI_INDEX_URL
              value: https://pypi.doubanio.com/simple/
            - name: SW_PYPI_TRUSTED_HOST
              value: pypi.doubanio.com
            - name: SW_PIP_CACHE_DIR
              value: /root/.cache/pip
      containers:
        - name: result-uploader
          imagePullPolicy: IfNotPresent
          image: amazon/aws-cli:2.7.25
          volumeMounts:
            - mountPath: /opt/starwhale
              name: data
          command:
            - sh
            - -c
            - >-
              aws --endpoint-url=$ENDPOINT_URL --region=$AWS_S3_REGION s3 cp /opt/starwhale/result/current $DST
      volumes:
        - name: pip-cache
          hostPath:
            path: /data
            type: DirectoryOrCreate
        - name: data
          emptyDir: {}
