apiVersion: batch/v1
kind: Job
metadata:
  name: "indexed-job"
  labels:
    owner: starwhale
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed
  template:
    metadata:
      labels:
        owner: starwhale
    spec:
      restartPolicy: Never
      containers:
        - name: "worker"
          image: "docker.io/library/busybox"
          args:
            - ppl
          volumeMounts:
            - mountPath: /root/.cache
              name: pip-cache
            - mountPath: /opt/starwhale
              name: data
          env:
            - name: SW_PIP_CACHE_DIR
              value: /root/.cache/pip
      volumes:
        - name: pip-cache
          hostPath:
            path: /data
            type: DirectoryOrCreate
        - name: data
          emptyDir: {}
