apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 'model-serving'
  labels:
    owner: starwhale
spec:
  selector:
    matchLabels:
      app: serve
  template:
    metadata:
      labels:
        app: serve
    spec:
      containers:
      - name: 'worker'
        image: 'docker.io/library/busybox'
        args:
        - serve
        volumeMounts:
        - mountPath: /root/.cache
          name: pip-cache
        - mountPath: /opt/starwhale
          name: data
        env:
        - name: SW_PIP_CACHE_DIR
          value: /root/.cache/pip
      volumes:
      - name: pip-cache
        hostPath:
          path: /data
          type: DirectoryOrCreate
      - name: data
        emptyDir: {}
