.POHNY: download
download:
	mkdir -p checkpoints/
	[ -f checkpoints/sam_vit_b_01ec64.pth] || wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth -O checkpoints/sam_vit_b_01ec64.pth
	#[ -f checkpoints/sam_vit_h_4b8939.pth] || wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth -O checkpoints/sam_vit_h_4b8939.pth
	#[ -f checkpoints/sam_vit_l_0b3195.pth] || wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth -O checkpoints/sam_vit_l_0b3195.pth