name: mnist

mode: generate

data_dir: data
data_filter: "t10k-image*"
label_filter: "t10k-label*"

process: mnist.process:DataSetProcessExecutor
pip_req: requirements.txt

desc: MNIST data and label test dataset
tag:
 - bin

attr:
  batch_size: 50
  alignment_size: 4k
  volume_size: 2M
