name: mnist

mode: generate
data_dir: data
process: process_api:MNISTProcess
pip_req: requirements.txt

desc: MNIST data and label test dataset
tag:
 - bin

attr:
  batch_size: 50
  alignment_size: 4k
  volume_size: 64M