FROM ubuntu:20.04

COPY external/sources.list /etc/apt/sources.list

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV TZ=Etc/UTC

# java opts
ARG JAVA_AGENT_OPTS ""
ENV JAVA_AGENT_OPTS=${JAVA_AGENT_OPTS}

# nvidia driver version
ARG NV_DRIVER_VERSION 470
ENV NV_DRIVER_VERSION ${NV_DRIVER_VERSION}

# Install os dependence\OpenJDK-11
RUN apt-get update \
    && apt-get install -y openjdk-11-jdk \
    && apt-get install -y --no-install-recommends nvidia-driver-${NV_DRIVER_VERSION} \
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/* /tmp/*

WORKDIR /opt/starwhale.java
# java jar
COPY jar/agent.jar agent.jar

ENTRYPOINT ["sh", "-c", "java ${JAVA_AGENT_OPTS} -jar agent.jar"]