FROM ubuntu:20.04

COPY external/sources.list /etc/apt/sources.list

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV TZ=Etc/UTC

# Install os dependence\OpenJDK-11
RUN apt-get update \
    && apt-get install -y openjdk-11-jre \
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/* /tmp/*
