export declare type Validator = (rule: any, value: any) => Promise<void>;
export declare const compose: (validators: Array<Validator | null>) => Validator;
export declare const required: (msg: string) => Validator;
export declare const number: Validator;
export declare const integer: (msg?: string) => Validator;
export declare const maxDecimal: (max: number) => Validator;
export declare const min: (flag: number, msg: string, inclusive?: boolean) => Validator;
export declare const max: (flag: number, msg: string, inclusive?: boolean) => Validator;
export declare const minLength: (flag: number, msg: string) => Validator;
export declare const maxLength: (flag: number, msg: string) => Validator;
export declare const passwordFormat: (msg?: string) => Validator;
export declare const shouldBeEqual: (val: any, msg: string) => Validator;
export declare const shouldNotBeEqual: (val: any, msg: string) => Validator;
