name: nmt

mode: generate

data_dir: data
data_filter: "test_eng-fra.txt"
label_filter: "test_eng-fra.txt"

process: code.dataset:DataSetProcessExecutor

desc: nmt data and label test dataset
tag:
 - bin

attr:
  batch_size: 100
  alignment_size: 4K
  volume_size: 2M
