name: nmt

mode: generate

data_dir: data
data_filter: "test*.txt"
label_filter: "test*.txt"

process: code.dataset:DataSetProcessExecutor

desc: nmt data and label test dataset
tag:
 - bin

attr:
  batch_size: 100
  alignment_size: 4M
  volume_size: 64M
