export const headerHeight = 56
export const sidebarExpandedWidth = 200
export const sidebarFoldedWidth = 68
export const textVariant = 'smallPlus'
export const dateFormat = 'YYYY-MM-DD'
export const dateWithZeroTimeFormat = 'YYYY-MM-DD 00:00:00'
export const dateTimeFormat = 'YYYY-MM-DD HH:mm:ss'
export const drawerExpandedWidthOfColumnManage = 520
export const passwordMinLength = 8
