apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  namespace: starwhale
  labels:
    role: agent

spec:
  selector:
    matchLabels:
      name: agent

  template:
    metadata:
      labels:
        name: agent
    spec:
      nodeSelector:
        starwhale.ai/node-domain: gpu
      containers:
        - name: agent
          image: starwhaleai/taskset:0.1.0-nightly-2022041601
          command: ["sleep"]
          args: ["3600000"]
          env:
            - name: DOCKER_HOST
              value: "127.0.0.1:2376"
          volumeMounts:
            - name: agent-storage
              mountPath: "/opt/starwhale"
              subPath: run
        - name: taskset
          image: starwhaleai/taskset:0.1.0-nightly-2022041601
          resources:
            requests:
              memory: 20Gi
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
              memory: 60Gi
          securityContext:
            privileged: true
          stdin: true
          tty: true
          volumeMounts:
            - name: agent-storage
              mountPath: "/var/lib/docker"
              subPath: dind
            - name: agent-storage
              mountPath: "/opt/starwhale"
              subPath: run
      volumes:
        - name: agent-storage
          hostPath:
            path: /mnt/data/starwhale/agent
            type: DirectoryOrCreate

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent-cpu
  namespace: starwhale
  labels:
    role: agent-cpu

spec:
  selector:
    matchLabels:
      name: agent-cpu

  template:
    metadata:
      labels:
        name: agent-cpu
    spec:
      nodeSelector:
        starwhale.ai/node-domain: cpu
      containers:
        - name: agent
          image: starwhaleai/taskset:0.1.0-nightly-2022041601
          command: ["sleep"]
          args: ["3600000"]
          env:
            - name: DOCKER_HOST
              value: "127.0.0.1:2376"
          volumeMounts:
            - name: agent-storage
              mountPath: "/opt/starwhale"
              subPath: run
        - name: taskset
          image: starwhaleai/taskset:0.1.0-nightly-2022041601
          resources:
            requests:
              memory: 5Gi
            limits:
              memory: 60Gi
          securityContext:
            privileged: true
          stdin: true
          tty: true
          volumeMounts:
            - name: agent-storage
              mountPath: "/var/lib/docker"
              subPath: dind
            - name: agent-storage
              mountPath: "/opt/starwhale"
              subPath: run
      volumes:
        - name: agent-storage
          hostPath:
            path: /mnt/data/starwhale/agent
            type: DirectoryOrCreate