apiVersion: v2
name: starwhale
description: StarWhale Platform Helm Charts
type: application
home: https://starwhale.ai
keywords:
  - "mlops"
maintainers:
  - name: "Starwhale Team"
    email: developer@starwhale.ai
    url: https://starwhale.ai/team
icon: https://github.com/star-whale/starwhale/raw/main/docs/static/img/logo_72x72px.png

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.16.0

version: "0.1.0"
appVersion: "latest"
