name: Python Client/SDK

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'client/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '