name: Console UI

on:
  push:
    branches:
      - main
      - feat/*
    paths-ignore:
      - 'console/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'console/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '