name: End to End Test

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  schedule:
    - cron: "34 10,13 * * *"
  pull_request:
    branches:
      - main

env:
  PYPI_RELEASE_VERSION: 100.0.0
  RELEASE_VERSION: 0.0.0-dev
  NEXUS_IMAGE: sonatype/nexus3:3.40.1
  NEXUS_USER_NAME: admin
  NEXUS_USER_PWD: admin123
  PORT_NEXUS: 8081
  PORT_CONTROLLER: 8082
  PORT_NEXUS_DOCKER: 8083
  IP_DOCKER_BRIDGE: 172.17.0.1
  REPO_NAME_DOCKER: docker-hosted
  REPO_NAME_PYPI: pypi-hosted

jobs:
  filter:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'
    outputs:
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}
      scripts: ${{ steps.filter.outputs.scripts }}
      docker: ${{ steps.filter.outputs.docker }}
      example: ${{ steps.filter.outputs.example }}
      labels: ${{ steps.pr-labels.outputs.labels }}

    steps:
      - uses: actions/checkout@v3
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - name: Check for files changed
        uses: getsentry/paths-filter@v2
        id: filter
        with:
          base: main
          filters: .github/file-filter.yml

  e2e-test:
    runs-on: ubuntu-latest

    needs:
      - filter
    if: ${{  github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || (github.event_name == 'pull_request' && (needs.filter.outputs.client == 'true' || needs.filter.outputs.server == 'true' || needs.filter.outputs.scripts == 'true' || needs.filter.outputs.docker == 'true' || needs.filter.outputs.example == 'true') && !contains(needs.filter.outputs.labels, 'ban-e2e'))}}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}
          architecture: "x64"

      # jar build
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "maven"
          server-id: starwhale # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: run e2e
        working-directory: ./scripts/e2e_test
        env:
          PYTHON_VERSION: ${{matrix.python-version}}
        run: ./start_test.sh
