name: End to End test for starwhale

on:
  schedule:
    - cron:  '34 10,13 * * *'

env:
  PYPI_RELEASE_VERSION: 100.0.0
  RELEASE_VERSION: 0.0.0-dev
  NEXUS_HOSTNAME: host.nexus
  NEXUS_IMAGE: sonatype/nexus3:3.40.1
  NEXUS_USER_NAME: admin
  NEXUS_USER_PWD: admin123
  PORT_NEXUS: 8081
  PORT_CONTROLLER: 8082
  PORT_NEXUS_DOCKER: 9001
  IP_DOCKER_COMPOSE_BRIDGE: 172.18.0.1
  SW_IMAGE_REPO: host.nexus:9001
  IP_DOCKER_BRIDGE: 172.17.0.1
  IP_DOCKER_COMPOSE_BRIDGE_RANGE: 172.0.0.0/8
  REPO_NAME_DOCKER: docker-hosted
  REPO_NAME_PYPI: pypi-hosted


jobs:
  e2e-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:

      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          architecture: "x64"


      # jar build
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "maven"
          server-id: starwhale # Value of the distributionManagement/repository/id field of the pom.xml



      - name: run e2e
        working-directory: ./scripts/e2e_test
        env:
          PYTHON_VERSION: 3.7
        run: ./start_test.sh