name: Maven Package For Server

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'server/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
